name: SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Target OS
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu' 
      - name: Build Dotnet
        run: dotnet build
      - name: Run Test 
        run: dotnet test 
      - name: Install .NET SDK
        run: |
         wget -O dotnet-install.sh https://dot.net/v1/dotnet-install.sh
         chmod +x dotnet-install.sh
         ./dotnet-install.sh --install-dir /usr/share/dotnet --channel LTS
         export PATH="$PATH:/usr/share/dotnet"
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner
      - name: SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"jci-bms-platform-dotnet" /o:"jci-bms-platform" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.it.reportsPaths="**/coverage.opencover.xml"
          dotnet build
          dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      - name: Dotnet Publish
        run: dotnet publish --configuration Release --output ./publish SonarTestApi.sln
      - name: List Publish Folder Contents
        run: ls -R ./publish
      - name: Install Veracode Static Analysis CLI
        run: |
          Invoke-WebRequest -Uri https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip -OutFile pipeline-scan-LATEST.zip
          Expand-Archive -Path pipeline-scan-LATEST.zip -DestinationPath pipeline-scan
